apiVersion: v1
kind: Service
metadata:
  name: sale 
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: sale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sale
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sale
  template:
    metadata:
      labels:
        app: sale
    spec:
      containers:
      - name: sale
        image: kimbahir/sale:latest
        imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sale
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: sale.bahir.dk 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sale
            port: 
              number: 80
  tls:
  - hosts:
    - sale.bahir.dk
    secretName: sale-bahir-dk-tls